import React from "react";
import {
  Document,
  Page,
  StyleSheet,
  Text,
  View,
  renderToBuffer,
} from "@react-pdf/renderer";

import type { AppLocale } from "@/lib/i18n/config";
import type { TaxReport, TaxReportRow } from "@/lib/tax/report";

const styles = StyleSheet.create({
  page: {
    backgroundColor: "#070707",
    color: "#F5F5F5",
    paddingTop: 28,
    paddingBottom: 28,
    paddingHorizontal: 28,
    fontSize: 9,
    fontFamily: "Helvetica",
  },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  brandText: {
    fontSize: 10,
    letterSpacing: 1.5,
    color: "#B8B8B8",
  },
  title: {
    fontSize: 12,
    fontWeight: 700,
    textAlign: "right",
  },
  subtitle: {
    marginTop: 2,
    color: "#B8B8B8",
    textAlign: "right",
  },
  summaryGrid: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 14,
  },
  statCard: {
    flexGrow: 1,
    flexBasis: 0,
    borderWidth: 1,
    borderColor: "#2B2B2B",
    backgroundColor: "#101010",
    padding: 8,
  },
  statLabel: {
    color: "#A8A8A8",
    marginBottom: 3,
    textTransform: "uppercase",
    fontSize: 8,
    letterSpacing: 0.8,
  },
  statValue: {
    fontSize: 11,
    fontWeight: 700,
  },
  table: {
    borderWidth: 1,
    borderColor: "#2B2B2B",
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#141414",
    borderBottomWidth: 1,
    borderBottomColor: "#2B2B2B",
    paddingVertical: 6,
    paddingHorizontal: 6,
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 5,
    paddingHorizontal: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#1B1B1B",
  },
  tableRowAlt: {
    backgroundColor: "#0D0D0D",
  },
  colDate: { width: "12%" },
  colOp: { width: "8%" },
  colAsset: { width: "12%" },
  colQuote: { width: "12%" },
  colValue: { width: "18%", textAlign: "right" },
  colRate: { width: "38%", textAlign: "right" },
  headerText: {
    color: "#BDBDBD",
    fontSize: 8,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  bodyText: {
    color: "#F2F2F2",
    fontSize: 8.5,
  },
  mutedText: {
    color: "#B8B8B8",
    fontSize: 8,
  },
  footer: {
    marginTop: 10,
    color: "#9A9A9A",
    fontSize: 7.5,
    lineHeight: 1.4,
  },
  pageNumber: {
    marginTop: 6,
    textAlign: "right",
    color: "#737373",
    fontSize: 7.5,
  },
});

const COPY = {
  en: {
    title: "PIT Report",
    yearLabel: "Year",
    allYears: "All years",
    totalBuys: "Total buys",
    totalSells: "Total sells",
    realizedPnl: "Realized PnL",
    tableDate: "Date",
    tableOp: "Op",
    tableAsset: "Asset",
    tableQuote: "Quote",
    tableValuePln: "Value PLN",
    tableRate: "Rate",
    footerNotice:
      "Generated by Logr for manual PIT statement preparation. Verify values before submission.",
    reportHash: "Report hash",
    page: "Page",
  },
  pl: {
    title: "Raport PIT",
    yearLabel: "Rok",
    allYears: "Wszystkie lata",
    totalBuys: "Suma kupna",
    totalSells: "Suma sprzedazy",
    realizedPnl: "Zrealizowany PnL",
    tableDate: "Data",
    tableOp: "Op",
    tableAsset: "Aktywum",
    tableQuote: "Waluta",
    tableValuePln: "Wartosc PLN",
    tableRate: "Kurs",
    footerNotice:
      "Wygenerowano przez Logr do recznego wypelnienia PIT. Zweryfikuj wartosci przed zlozeniem.",
    reportHash: "Hash raportu",
    page: "Strona",
  },
} as const;

function chunkRows(rows: TaxReportRow[], size: number) {
  const result: TaxReportRow[][] = [];
  for (let index = 0; index < rows.length; index += size) {
    result.push(rows.slice(index, index + size));
  }
  return result;
}

function summarize(report: TaxReport) {
  return report.rows.reduce(
    (acc, row) => {
      const value = Number(row.valuePln);
      if (row.operation === "BUY") {
        acc.buyValue += value;
      } else {
        acc.sellValue += value;
      }
      return acc;
    },
    { buyValue: 0, sellValue: 0 },
  );
}

function formatAmount(value: number) {
  return `${value.toFixed(2)} PLN`;
}

export async function renderTaxReportPdf(report: TaxReport, locale: AppLocale) {
  const copy = COPY[locale] ?? COPY.en;
  const rowsByPage = chunkRows(report.rows, 24);
  const pages = rowsByPage.length > 0 ? rowsByPage : [[]];
  const summary = summarize(report);
  const pnl = summary.sellValue - summary.buyValue;
  const yearLabel = report.year ?? copy.allYears;

  const doc = (
    <Document title={`Logr ${copy.title} ${yearLabel}`}>
      {pages.map((rows, pageIndex) => (
        <Page key={`${yearLabel}-${pageIndex}`} size="A4" style={styles.page}>
          <View style={styles.header}>
            <Text style={styles.brandText}>LOGR</Text>
            <View>
              <Text style={styles.title}>{copy.title}</Text>
              <Text style={styles.subtitle}>
                {copy.yearLabel}: {String(yearLabel)}
              </Text>
            </View>
          </View>

          {pageIndex === 0 ? (
            <View style={styles.summaryGrid}>
              <View style={styles.statCard}>
                <Text style={styles.statLabel}>{copy.totalBuys}</Text>
                <Text style={styles.statValue}>{formatAmount(summary.buyValue)}</Text>
              </View>
              <View style={styles.statCard}>
                <Text style={styles.statLabel}>{copy.totalSells}</Text>
                <Text style={styles.statValue}>{formatAmount(summary.sellValue)}</Text>
              </View>
              <View style={styles.statCard}>
                <Text style={styles.statLabel}>{copy.realizedPnl}</Text>
                <Text style={styles.statValue}>{formatAmount(pnl)}</Text>
              </View>
            </View>
          ) : null}

          <View style={styles.table}>
            <View style={styles.tableHeader}>
              <Text style={[styles.headerText, styles.colDate]}>{copy.tableDate}</Text>
              <Text style={[styles.headerText, styles.colOp]}>{copy.tableOp}</Text>
              <Text style={[styles.headerText, styles.colAsset]}>{copy.tableAsset}</Text>
              <Text style={[styles.headerText, styles.colQuote]}>{copy.tableQuote}</Text>
              <Text style={[styles.headerText, styles.colValue]}>{copy.tableValuePln}</Text>
              <Text style={[styles.headerText, styles.colRate]}>{copy.tableRate}</Text>
            </View>

            {rows.map((row, rowIndex) => {
              const rowStyle = rowIndex % 2 === 1 ? [styles.tableRow, styles.tableRowAlt] : styles.tableRow;
              const ratePair = `${row.rate.value} ${row.quoteCurrency}/PLN`;

              return (
                <View key={row.entryId} style={rowStyle}>
                  <Text style={[styles.bodyText, styles.colDate]}>{row.date}</Text>
                  <Text style={[styles.bodyText, styles.colOp]}>{row.operation}</Text>
                  <Text style={[styles.bodyText, styles.colAsset]}>{row.baseAsset}</Text>
                  <Text style={[styles.bodyText, styles.colQuote]}>{row.quoteCurrency}</Text>
                  <Text style={[styles.bodyText, styles.colValue]}>{row.valuePln} PLN</Text>
                  <Text style={[styles.bodyText, styles.colRate]}>{ratePair}</Text>
                </View>
              );
            })}
          </View>

          <Text style={styles.footer}>
            {copy.footerNotice}
          </Text>
          <Text style={styles.footer}>
            {copy.reportHash}: {report.reportHash}
          </Text>
          <Text style={styles.pageNumber}>
            {copy.page} {pageIndex + 1} / {pages.length}
          </Text>
        </Page>
      ))}
    </Document>
  );

  return renderToBuffer(doc);
}
